### PR TITLE
Course page

### PR DESCRIPTION
**Pull request by MelvinTham**
not completed yet. Hopefully, it'll be done before the first iteration. However, asking questions is currently working.

### CODE REVIEW

**Comment by MelvinTham** [comment]
hey @andywang219, I've pulled this and tested it. I like your changes with the create questions. Great job.

**Comment by Charding96** [comment]
Nicely Done.

**Comment by andywang219** [comment]
When you enroll in a course, you can enter the course page by clicking the course name. Afterward, if there're questions, it'll show up and you can click the question -> redirect you to the question page. In the question page, you can see the replies and submit a reply yourself.

**Comment by mjacome0** [comment]
Glad to see that course questions are up and running

**Pull request merged**
